apiVersion: v1
kind: ConfigMap
metadata:
  name: vdlg-video-processor-config
  namespace: vdlg
data:
  ENV: "dev"
  PORT: "8080"
  INPUT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/458397709109/input-queue" 
  AWS_REGION: "us-east-1"
  AWS_USE_CREDENTIALS: "true"