apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vdlg-video-processor
  namespace: vdlg
  labels:
    app: vdlg-video-processor
    environment: "dev"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vdlg-video-processor
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
