name: DestroyApplication

on:
  workflow_dispatch:
  
jobs:
  destroy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Attach to EKS cluster
        run: aws eks update-kubeconfig --region us-east-1 --name vdlg-eks-cluster

      - name: Deploy to EKS
        run: make kube-deploy-eks-destroy